/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cargo.gltf --jsx --outDir=path/to/output/directory\ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cargo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} position={[-0.068, 1.281, -0.019]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1.288, 1.086, 3.745]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} position={[-0.068, -0.154, 1.334]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.288, 1.086, 3.745]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[-0.068, -0.116, -1.447]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.288, 1.086, 3.745]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.Material} position={[-4.086, -0.149, -0.017]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.288, 1.086, 3.745]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.Material} position={[4.021, -0.095, -0.025]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.271} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.metal} position={[4.124, -0.116, 0.332]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.039, 1.269, 0.039]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.metal} position={[4.124, -0.116, 0.837]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.039, 1.269, 0.039]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.metal} position={[4.124, -0.116, -0.36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.039, 1.269, 0.039]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.metal} position={[4.124, -0.116, -0.865]} rotation={[0, -Math.PI / 2, 0]} scale={[0.039, 1.269, 0.039]} />
    </group>
  )
}

useGLTF.preload('/cargo.gltf')
